comment 'JQueery'
yieldUnescaped '<script src="/theme/jquery/dist/jquery.min.js"></script>'
comment 'Bootstrap'  
yieldUnescaped  '<script src="/theme/bootstrap/dist/js/bootstrap.min.js"></script>'
comment 'FastClick'  
yieldUnescaped '<script src="/theme/fastclick/lib/fastclick.js"></script>'
comment 'NProgress'  
yieldUnescaped '<script src="/theme/nprogress/nprogress.js"></script>'
comment 'Chart.js'  
yieldUnescaped '<script src="/theme/Chart.js/dist/Chart.min.js"></script>'
comment 'Gauge.js'   
yieldUnescaped '<script src="/theme/gauge.js/dist/gauge.min.js"></script>'
comment 'Bootstrap-progressbar'   
yieldUnescaped '<script src="/theme/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>'
comment 'iCheck'  
yieldUnescaped '<script src="/theme/iCheck/icheck.min.js"></script>'
comment 'SkyIcons'
yieldUnescaped '<script src="/theme/skycons/skycons.js"></script>'
comment 'Flot'
yieldUnescaped '<script src="/theme/Flot/jquery.flot.js"></script>'
yieldUnescaped '<script src="/theme/Flot/jquery.flot.pie.js"></script>'
yieldUnescaped '<script src="/theme/Flot/jquery.flot.time.js"></script>'
yieldUnescaped '<script src="/theme/Flot/jquery.flot.stack.js"></script>'
yieldUnescaped '<script src="/theme/Flot/jquery.flot.resize.js"></script>'

comment 'Flot plugins'	   
yieldUnescaped '<script src="/theme/flot.orderbars/js/jquery.flot.orderBars.js"></script>'
yieldUnescaped '<script src="/theme/flot-spline/js/jquery.flot.spline.min.js"></script>'
yieldUnescaped '<script src="/theme/flot.curvedlines/curvedLines.js"></script>'
	comment 'DateJS'
yieldUnescaped '<script src="/theme/DateJS/build/date.js"></script>'
comment 'JQVMap'
yieldUnescaped '<script src="/theme/jqvmap/dist/jquery.vmap.js"></script>'
yieldUnescaped '<script src="/theme/jqvmap/dist/maps/jquery.vmap.world.js"></script>'
yieldUnescaped '<script src="/theme/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>'
comment 'Bootstrap-daterangepicker'    
yieldUnescaped '<script src="/theme/moment/min/moment.min.js"></script>'
yieldUnescaped '<script src="/theme/bootstrap-daterangepicker/daterangepicker.js"></script>'
comment 'Custom Theme Scripts'
yieldUnescaped '<script src="/js/custom.min.js"></script>'